apiVersion: v1
kind: Service
metadata:
  name: svc-frontend
  namespace: ns-stocksanalyzer
spec:
  type: ClusterIP
  selector:     
    pl-app: stocksanalyzer
    pl-version: 1.0.230
    pl-component: frontend
    pl-env: prod

  ports:
    - protocol: TCP
      port: 80
      #targetPort: 8501
      #targetPort: 8000

