apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpl-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      pl-app: stocksanalyzer
      pl-version: 1.0.297
      pl-component: database
      pl-env: prod
  template:
    metadata:
      labels:
        pl-app: stocksanalyzer
        pl-version: 1.0.297
        pl-component: database
        pl-env: prod
    spec:
      containers:
        - name: postgres
          image: 'postgres:17.0'
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5432
          envFrom:
            - configMapRef:
                name: cmp-postgres
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: vol-postgres-data
      volumes:
        - name: vol-postgres-data
          persistentVolumeClaim:
            claimName: pvc-postgres