apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-postgres
  namespace: ns-stocksanalyzer
  labels:
    pl-app: stocksanalyzer
    pl-component: database
spec:
  accessModes:
    - ReadWriteMany 
  resources:
    requests:
      storage: 10Gi 
  storageClassName: "" 
  volumeName: pvl-postgres
