apiVersion: v1
kind: PersistentVolume
metadata:
  name: pvl-postgres
spec:
  claimRef:
    name: pvc-postgres
    namespace: ns-stocksanalyzer
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  hostPath:
    path: /postgres-data
    type: DirectoryOrCreate
  nodeAffinity:
    required:
      nodeSelectorTerms:
      - matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - acg-worker1