apiVersion: v1
kind: Service
metadata:
  name: svc-postgres
  labels:
    pl-app: stocksanalyzer
    pl-version: 1.0.297
    pl-component: database
    pl-env: prod
spec:
  type: NodePort
  ports:
    - port: 5432
  selector:
    pl-app: stocksanalyzer
    pl-version: 1.0.297
    pl-component: database
    pl-env: prod